### PR TITLE
SEO-2684-Coverage-Page-With-Redirect-UG

### PR DESCRIPTION
**Pull request by gowthamanthavasiyappan**
Hi @ChristoIssac,

|Task Category| Pages With Redirect - Search console|
|:--|:--|
|Issue count| Help site links - 1000 |
|Fixed Count| Help site links - 5 |
|Analysis| Inspecting the links and found referring pages |
|Solution| replaced the exact URL instead of old URL |
|Hotfix PR| https://github.com/syncfusion-content/asp.netwebforms-docs/pull/260 | 
|Task link|https://syncfusion.atlassian.net/browse/SEO-2684|
|Excel| N/A |

Regards,
Gowthaman

### CODE REVIEW

**Comment by gowthamanthavasiyappan** [comment]
rebuild

**Comment by kannans24** [comment]
rebuild

**Comment by kannans24** [comment]
rebuild

**Review by Aishwarya-Ganesan — APPROVED** [review]
Changes are Fine.

**Pull request merged**
